version: '3.7'

services:
  # POSTGRESQL
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - postgres-volume:/var/lib/postgres
      - *.sql/docker-entrypoint-initdb.d/init.sql
    enviroment:
	POSTGRES_PASSWORD: qwerty
	POSTGRES_DB: desarrollo
	
    networks:
      - postgres-network
    # restart: always


  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - postgres-network
    depends_on:
      - postgres
